/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ShellAuthedRouteRouteImport } from './routes/_shell/_authed/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as ShellDiscoverIndexRouteImport } from './routes/_shell/discover/index'
import { Route as ShellPricingIndexRouteImport } from './routes/_shell/pricing/index'
import { Route as ShellStartupSlugRouteImport } from './routes/_shell/startup/$slug'
import { Route as AppExploreIndexRouteImport } from './routes/app/explore/index'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages/index'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/app/opportunities/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppStartupIndexRouteImport } from './routes/app/startup/index'
import { Route as AppStartupsNewRouteImport } from './routes/app/startups/new'
import { Route as AppTeamIndexRouteImport } from './routes/app/team/index'
import { Route as AppTrialsIndexRouteImport } from './routes/app/trials/index'
import { Route as AppTrialsTrialCycleIdRouteImport } from './routes/app/trials/$trialCycleId'
import { Route as AppUpgradeIndexRouteImport } from './routes/app/upgrade/index'
import { Route as AppWorkIndexRouteImport } from './routes/app/work/index'
import { Route as ShellAuthedInboxIndexRouteImport } from './routes/_shell/_authed/inbox/index'
import { Route as ShellAuthedMyPulsesIndexRouteImport } from './routes/_shell/_authed/my-pulses/index'
import { Route as ShellAuthedProfileIndexRouteImport } from './routes/_shell/_authed/profile/index'
import { Route as ShellAuthedSSlugRouteRouteImport } from './routes/_shell/_authed/s/$slug/route'
import { Route as ShellAuthedStartupsNewRouteImport } from './routes/_shell/_authed/startups/new'
import { Route as ShellAuthedThreadsIndexRouteImport } from './routes/_shell/_authed/threads/index'
import { Route as AppStartupRolesNewRouteImport } from './routes/app/startup/roles/new'
import { Route as AppStartupTrialsNewRouteImport } from './routes/app/startup/trials/new'
import { Route as ShellAuthedSSlugIndexRouteImport } from './routes/_shell/_authed/s/$slug/index'
import { Route as ShellAuthedSSlugMemberRouteRouteImport } from './routes/_shell/_authed/s/$slug/_member/route'
import { Route as ShellAuthedSSlugTrialsTrialCycleIdRouteImport } from './routes/_shell/_authed/s/$slug/trials/$trialCycleId'
import { Route as ShellAuthedSSlugMemberActivityIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/activity/index'
import { Route as ShellAuthedSSlugMemberCyclesIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/cycles/index'
import { Route as ShellAuthedSSlugMemberCyclesCycleIdRouteImport } from './routes/_shell/_authed/s/$slug/_member/cycles/$cycleId'
import { Route as ShellAuthedSSlugMemberHiringIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/hiring/index'
import { Route as ShellAuthedSSlugMemberPitchIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/pitch/index'
import { Route as ShellAuthedSSlugMemberSettingsIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/settings/index'
import { Route as ShellAuthedSSlugMemberTeamIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/team/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAuthedRouteRoute = ShellAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => ShellRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDiscoverIndexRoute = ShellDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPricingIndexRoute = ShellPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellStartupSlugRoute = ShellStartupSlugRouteImport.update({
  id: '/startup/$slug',
  path: '/startup/$slug',
  getParentRoute: () => ShellRouteRoute,
} as any)
const AppExploreIndexRoute = AppExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStartupIndexRoute = AppStartupIndexRouteImport.update({
  id: '/startup/',
  path: '/startup/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStartupsNewRoute = AppStartupsNewRouteImport.update({
  id: '/startups/new',
  path: '/startups/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrialsIndexRoute = AppTrialsIndexRouteImport.update({
  id: '/trials/',
  path: '/trials/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrialsTrialCycleIdRoute = AppTrialsTrialCycleIdRouteImport.update({
  id: '/trials/$trialCycleId',
  path: '/trials/$trialCycleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUpgradeIndexRoute = AppUpgradeIndexRouteImport.update({
  id: '/upgrade/',
  path: '/upgrade/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkIndexRoute = AppWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShellAuthedInboxIndexRoute = ShellAuthedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedMyPulsesIndexRoute =
  ShellAuthedMyPulsesIndexRouteImport.update({
    id: '/my-pulses/',
    path: '/my-pulses/',
    getParentRoute: () => ShellAuthedRouteRoute,
  } as any)
const ShellAuthedProfileIndexRoute = ShellAuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedSSlugRouteRoute = ShellAuthedSSlugRouteRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedStartupsNewRoute = ShellAuthedStartupsNewRouteImport.update({
  id: '/startups/new',
  path: '/startups/new',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedThreadsIndexRoute = ShellAuthedThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const AppStartupRolesNewRoute = AppStartupRolesNewRouteImport.update({
  id: '/startup/roles/new',
  path: '/startup/roles/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStartupTrialsNewRoute = AppStartupTrialsNewRouteImport.update({
  id: '/startup/trials/new',
  path: '/startup/trials/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShellAuthedSSlugIndexRoute = ShellAuthedSSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAuthedSSlugRouteRoute,
} as any)
const ShellAuthedSSlugMemberRouteRoute =
  ShellAuthedSSlugMemberRouteRouteImport.update({
    id: '/_member',
    getParentRoute: () => ShellAuthedSSlugRouteRoute,
  } as any)
const ShellAuthedSSlugTrialsTrialCycleIdRoute =
  ShellAuthedSSlugTrialsTrialCycleIdRouteImport.update({
    id: '/trials/$trialCycleId',
    path: '/trials/$trialCycleId',
    getParentRoute: () => ShellAuthedSSlugRouteRoute,
  } as any)
const ShellAuthedSSlugMemberActivityIndexRoute =
  ShellAuthedSSlugMemberActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberCyclesIndexRoute =
  ShellAuthedSSlugMemberCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberCyclesCycleIdRoute =
  ShellAuthedSSlugMemberCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberHiringIndexRoute =
  ShellAuthedSSlugMemberHiringIndexRouteImport.update({
    id: '/hiring/',
    path: '/hiring/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberPitchIndexRoute =
  ShellAuthedSSlugMemberPitchIndexRouteImport.update({
    id: '/pitch/',
    path: '/pitch/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberSettingsIndexRoute =
  ShellAuthedSSlugMemberSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberTeamIndexRoute =
  ShellAuthedSSlugMemberTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/app/': typeof AppIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/startup/$slug': typeof ShellStartupSlugRoute
  '/app/startups/new': typeof AppStartupsNewRoute
  '/app/trials/$trialCycleId': typeof AppTrialsTrialCycleIdRoute
  '/discover/': typeof ShellDiscoverIndexRoute
  '/pricing/': typeof ShellPricingIndexRoute
  '/app/explore/': typeof AppExploreIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/startup/': typeof AppStartupIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
  '/app/trials/': typeof AppTrialsIndexRoute
  '/app/upgrade/': typeof AppUpgradeIndexRoute
  '/app/work/': typeof AppWorkIndexRoute
  '/s/$slug': typeof ShellAuthedSSlugRouteRouteWithChildren
  '/startups/new': typeof ShellAuthedStartupsNewRoute
  '/app/startup/roles/new': typeof AppStartupRolesNewRoute
  '/app/startup/trials/new': typeof AppStartupTrialsNewRoute
  '/inbox/': typeof ShellAuthedInboxIndexRoute
  '/my-pulses/': typeof ShellAuthedMyPulsesIndexRoute
  '/profile/': typeof ShellAuthedProfileIndexRoute
  '/threads/': typeof ShellAuthedThreadsIndexRoute
  '/s/$slug/': typeof ShellAuthedSSlugIndexRoute
  '/s/$slug/trials/$trialCycleId': typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
  '/s/$slug/cycles/$cycleId': typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  '/s/$slug/activity/': typeof ShellAuthedSSlugMemberActivityIndexRoute
  '/s/$slug/cycles/': typeof ShellAuthedSSlugMemberCyclesIndexRoute
  '/s/$slug/hiring/': typeof ShellAuthedSSlugMemberHiringIndexRoute
  '/s/$slug/pitch/': typeof ShellAuthedSSlugMemberPitchIndexRoute
  '/s/$slug/settings/': typeof ShellAuthedSSlugMemberSettingsIndexRoute
  '/s/$slug/team/': typeof ShellAuthedSSlugMemberTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/app': typeof AppIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/startup/$slug': typeof ShellStartupSlugRoute
  '/app/startups/new': typeof AppStartupsNewRoute
  '/app/trials/$trialCycleId': typeof AppTrialsTrialCycleIdRoute
  '/discover': typeof ShellDiscoverIndexRoute
  '/pricing': typeof ShellPricingIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/opportunities': typeof AppOpportunitiesIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/startup': typeof AppStartupIndexRoute
  '/app/team': typeof AppTeamIndexRoute
  '/app/trials': typeof AppTrialsIndexRoute
  '/app/upgrade': typeof AppUpgradeIndexRoute
  '/app/work': typeof AppWorkIndexRoute
  '/startups/new': typeof ShellAuthedStartupsNewRoute
  '/app/startup/roles/new': typeof AppStartupRolesNewRoute
  '/app/startup/trials/new': typeof AppStartupTrialsNewRoute
  '/inbox': typeof ShellAuthedInboxIndexRoute
  '/my-pulses': typeof ShellAuthedMyPulsesIndexRoute
  '/profile': typeof ShellAuthedProfileIndexRoute
  '/threads': typeof ShellAuthedThreadsIndexRoute
  '/s/$slug': typeof ShellAuthedSSlugIndexRoute
  '/s/$slug/trials/$trialCycleId': typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
  '/s/$slug/cycles/$cycleId': typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  '/s/$slug/activity': typeof ShellAuthedSSlugMemberActivityIndexRoute
  '/s/$slug/cycles': typeof ShellAuthedSSlugMemberCyclesIndexRoute
  '/s/$slug/hiring': typeof ShellAuthedSSlugMemberHiringIndexRoute
  '/s/$slug/pitch': typeof ShellAuthedSSlugMemberPitchIndexRoute
  '/s/$slug/settings': typeof ShellAuthedSSlugMemberSettingsIndexRoute
  '/s/$slug/team': typeof ShellAuthedSSlugMemberTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/_shell/_authed': typeof ShellAuthedRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/app/': typeof AppIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/_shell/startup/$slug': typeof ShellStartupSlugRoute
  '/app/startups/new': typeof AppStartupsNewRoute
  '/app/trials/$trialCycleId': typeof AppTrialsTrialCycleIdRoute
  '/_shell/discover/': typeof ShellDiscoverIndexRoute
  '/_shell/pricing/': typeof ShellPricingIndexRoute
  '/app/explore/': typeof AppExploreIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/startup/': typeof AppStartupIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
  '/app/trials/': typeof AppTrialsIndexRoute
  '/app/upgrade/': typeof AppUpgradeIndexRoute
  '/app/work/': typeof AppWorkIndexRoute
  '/_shell/_authed/s/$slug': typeof ShellAuthedSSlugRouteRouteWithChildren
  '/_shell/_authed/startups/new': typeof ShellAuthedStartupsNewRoute
  '/app/startup/roles/new': typeof AppStartupRolesNewRoute
  '/app/startup/trials/new': typeof AppStartupTrialsNewRoute
  '/_shell/_authed/inbox/': typeof ShellAuthedInboxIndexRoute
  '/_shell/_authed/my-pulses/': typeof ShellAuthedMyPulsesIndexRoute
  '/_shell/_authed/profile/': typeof ShellAuthedProfileIndexRoute
  '/_shell/_authed/threads/': typeof ShellAuthedThreadsIndexRoute
  '/_shell/_authed/s/$slug/_member': typeof ShellAuthedSSlugMemberRouteRouteWithChildren
  '/_shell/_authed/s/$slug/': typeof ShellAuthedSSlugIndexRoute
  '/_shell/_authed/s/$slug/trials/$trialCycleId': typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
  '/_shell/_authed/s/$slug/_member/cycles/$cycleId': typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  '/_shell/_authed/s/$slug/_member/activity/': typeof ShellAuthedSSlugMemberActivityIndexRoute
  '/_shell/_authed/s/$slug/_member/cycles/': typeof ShellAuthedSSlugMemberCyclesIndexRoute
  '/_shell/_authed/s/$slug/_member/hiring/': typeof ShellAuthedSSlugMemberHiringIndexRoute
  '/_shell/_authed/s/$slug/_member/pitch/': typeof ShellAuthedSSlugMemberPitchIndexRoute
  '/_shell/_authed/s/$slug/_member/settings/': typeof ShellAuthedSSlugMemberSettingsIndexRoute
  '/_shell/_authed/s/$slug/_member/team/': typeof ShellAuthedSSlugMemberTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/invite/$token'
    | '/u/$username'
    | '/app/'
    | '/explore/'
    | '/startup/$slug'
    | '/app/startups/new'
    | '/app/trials/$trialCycleId'
    | '/discover/'
    | '/pricing/'
    | '/app/explore/'
    | '/app/messages/'
    | '/app/opportunities/'
    | '/app/profile/'
    | '/app/startup/'
    | '/app/team/'
    | '/app/trials/'
    | '/app/upgrade/'
    | '/app/work/'
    | '/s/$slug'
    | '/startups/new'
    | '/app/startup/roles/new'
    | '/app/startup/trials/new'
    | '/inbox/'
    | '/my-pulses/'
    | '/profile/'
    | '/threads/'
    | '/s/$slug/'
    | '/s/$slug/trials/$trialCycleId'
    | '/s/$slug/cycles/$cycleId'
    | '/s/$slug/activity/'
    | '/s/$slug/cycles/'
    | '/s/$slug/hiring/'
    | '/s/$slug/pitch/'
    | '/s/$slug/settings/'
    | '/s/$slug/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/u/$username'
    | '/app'
    | '/explore'
    | '/startup/$slug'
    | '/app/startups/new'
    | '/app/trials/$trialCycleId'
    | '/discover'
    | '/pricing'
    | '/app/explore'
    | '/app/messages'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/startup'
    | '/app/team'
    | '/app/trials'
    | '/app/upgrade'
    | '/app/work'
    | '/startups/new'
    | '/app/startup/roles/new'
    | '/app/startup/trials/new'
    | '/inbox'
    | '/my-pulses'
    | '/profile'
    | '/threads'
    | '/s/$slug'
    | '/s/$slug/trials/$trialCycleId'
    | '/s/$slug/cycles/$cycleId'
    | '/s/$slug/activity'
    | '/s/$slug/cycles'
    | '/s/$slug/hiring'
    | '/s/$slug/pitch'
    | '/s/$slug/settings'
    | '/s/$slug/team'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/app'
    | '/_shell/_authed'
    | '/invite/$token'
    | '/u/$username'
    | '/app/'
    | '/explore/'
    | '/_shell/startup/$slug'
    | '/app/startups/new'
    | '/app/trials/$trialCycleId'
    | '/_shell/discover/'
    | '/_shell/pricing/'
    | '/app/explore/'
    | '/app/messages/'
    | '/app/opportunities/'
    | '/app/profile/'
    | '/app/startup/'
    | '/app/team/'
    | '/app/trials/'
    | '/app/upgrade/'
    | '/app/work/'
    | '/_shell/_authed/s/$slug'
    | '/_shell/_authed/startups/new'
    | '/app/startup/roles/new'
    | '/app/startup/trials/new'
    | '/_shell/_authed/inbox/'
    | '/_shell/_authed/my-pulses/'
    | '/_shell/_authed/profile/'
    | '/_shell/_authed/threads/'
    | '/_shell/_authed/s/$slug/_member'
    | '/_shell/_authed/s/$slug/'
    | '/_shell/_authed/s/$slug/trials/$trialCycleId'
    | '/_shell/_authed/s/$slug/_member/cycles/$cycleId'
    | '/_shell/_authed/s/$slug/_member/activity/'
    | '/_shell/_authed/s/$slug/_member/cycles/'
    | '/_shell/_authed/s/$slug/_member/hiring/'
    | '/_shell/_authed/s/$slug/_member/pitch/'
    | '/_shell/_authed/s/$slug/_member/settings/'
    | '/_shell/_authed/s/$slug/_member/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  UUsernameRoute: typeof UUsernameRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_authed': {
      id: '/_shell/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellAuthedRouteRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/discover/': {
      id: '/_shell/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof ShellDiscoverIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pricing/': {
      id: '/_shell/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof ShellPricingIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/startup/$slug': {
      id: '/_shell/startup/$slug'
      path: '/startup/$slug'
      fullPath: '/startup/$slug'
      preLoaderRoute: typeof ShellStartupSlugRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/app/explore/': {
      id: '/app/explore/'
      path: '/explore'
      fullPath: '/app/explore/'
      preLoaderRoute: typeof AppExploreIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/opportunities/': {
      id: '/app/opportunities/'
      path: '/opportunities'
      fullPath: '/app/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/startup/': {
      id: '/app/startup/'
      path: '/startup'
      fullPath: '/app/startup/'
      preLoaderRoute: typeof AppStartupIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/startups/new': {
      id: '/app/startups/new'
      path: '/startups/new'
      fullPath: '/app/startups/new'
      preLoaderRoute: typeof AppStartupsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team/': {
      id: '/app/team/'
      path: '/team'
      fullPath: '/app/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/trials/': {
      id: '/app/trials/'
      path: '/trials'
      fullPath: '/app/trials/'
      preLoaderRoute: typeof AppTrialsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/trials/$trialCycleId': {
      id: '/app/trials/$trialCycleId'
      path: '/trials/$trialCycleId'
      fullPath: '/app/trials/$trialCycleId'
      preLoaderRoute: typeof AppTrialsTrialCycleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/upgrade/': {
      id: '/app/upgrade/'
      path: '/upgrade'
      fullPath: '/app/upgrade/'
      preLoaderRoute: typeof AppUpgradeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/work/': {
      id: '/app/work/'
      path: '/work'
      fullPath: '/app/work/'
      preLoaderRoute: typeof AppWorkIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_shell/_authed/inbox/': {
      id: '/_shell/_authed/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof ShellAuthedInboxIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/my-pulses/': {
      id: '/_shell/_authed/my-pulses/'
      path: '/my-pulses'
      fullPath: '/my-pulses/'
      preLoaderRoute: typeof ShellAuthedMyPulsesIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/profile/': {
      id: '/_shell/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ShellAuthedProfileIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/s/$slug': {
      id: '/_shell/_authed/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof ShellAuthedSSlugRouteRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/startups/new': {
      id: '/_shell/_authed/startups/new'
      path: '/startups/new'
      fullPath: '/startups/new'
      preLoaderRoute: typeof ShellAuthedStartupsNewRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/threads/': {
      id: '/_shell/_authed/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ShellAuthedThreadsIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/app/startup/roles/new': {
      id: '/app/startup/roles/new'
      path: '/startup/roles/new'
      fullPath: '/app/startup/roles/new'
      preLoaderRoute: typeof AppStartupRolesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/startup/trials/new': {
      id: '/app/startup/trials/new'
      path: '/startup/trials/new'
      fullPath: '/app/startup/trials/new'
      preLoaderRoute: typeof AppStartupTrialsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_shell/_authed/s/$slug/': {
      id: '/_shell/_authed/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof ShellAuthedSSlugIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugRouteRoute
    }
    '/_shell/_authed/s/$slug/_member': {
      id: '/_shell/_authed/s/$slug/_member'
      path: ''
      fullPath: '/s/$slug'
      preLoaderRoute: typeof ShellAuthedSSlugMemberRouteRouteImport
      parentRoute: typeof ShellAuthedSSlugRouteRoute
    }
    '/_shell/_authed/s/$slug/trials/$trialCycleId': {
      id: '/_shell/_authed/s/$slug/trials/$trialCycleId'
      path: '/trials/$trialCycleId'
      fullPath: '/s/$slug/trials/$trialCycleId'
      preLoaderRoute: typeof ShellAuthedSSlugTrialsTrialCycleIdRouteImport
      parentRoute: typeof ShellAuthedSSlugRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/activity/': {
      id: '/_shell/_authed/s/$slug/_member/activity/'
      path: '/activity'
      fullPath: '/s/$slug/activity/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberActivityIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/cycles/': {
      id: '/_shell/_authed/s/$slug/_member/cycles/'
      path: '/cycles'
      fullPath: '/s/$slug/cycles/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberCyclesIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/cycles/$cycleId': {
      id: '/_shell/_authed/s/$slug/_member/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/s/$slug/cycles/$cycleId'
      preLoaderRoute: typeof ShellAuthedSSlugMemberCyclesCycleIdRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/hiring/': {
      id: '/_shell/_authed/s/$slug/_member/hiring/'
      path: '/hiring'
      fullPath: '/s/$slug/hiring/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberHiringIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/pitch/': {
      id: '/_shell/_authed/s/$slug/_member/pitch/'
      path: '/pitch'
      fullPath: '/s/$slug/pitch/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberPitchIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/settings/': {
      id: '/_shell/_authed/s/$slug/_member/settings/'
      path: '/settings'
      fullPath: '/s/$slug/settings/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberSettingsIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/team/': {
      id: '/_shell/_authed/s/$slug/_member/team/'
      path: '/team'
      fullPath: '/s/$slug/team/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberTeamIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
  }
}

interface ShellAuthedSSlugMemberRouteRouteChildren {
  ShellAuthedSSlugMemberCyclesCycleIdRoute: typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  ShellAuthedSSlugMemberActivityIndexRoute: typeof ShellAuthedSSlugMemberActivityIndexRoute
  ShellAuthedSSlugMemberCyclesIndexRoute: typeof ShellAuthedSSlugMemberCyclesIndexRoute
  ShellAuthedSSlugMemberHiringIndexRoute: typeof ShellAuthedSSlugMemberHiringIndexRoute
  ShellAuthedSSlugMemberPitchIndexRoute: typeof ShellAuthedSSlugMemberPitchIndexRoute
  ShellAuthedSSlugMemberSettingsIndexRoute: typeof ShellAuthedSSlugMemberSettingsIndexRoute
  ShellAuthedSSlugMemberTeamIndexRoute: typeof ShellAuthedSSlugMemberTeamIndexRoute
}

const ShellAuthedSSlugMemberRouteRouteChildren: ShellAuthedSSlugMemberRouteRouteChildren =
  {
    ShellAuthedSSlugMemberCyclesCycleIdRoute:
      ShellAuthedSSlugMemberCyclesCycleIdRoute,
    ShellAuthedSSlugMemberActivityIndexRoute:
      ShellAuthedSSlugMemberActivityIndexRoute,
    ShellAuthedSSlugMemberCyclesIndexRoute:
      ShellAuthedSSlugMemberCyclesIndexRoute,
    ShellAuthedSSlugMemberHiringIndexRoute:
      ShellAuthedSSlugMemberHiringIndexRoute,
    ShellAuthedSSlugMemberPitchIndexRoute:
      ShellAuthedSSlugMemberPitchIndexRoute,
    ShellAuthedSSlugMemberSettingsIndexRoute:
      ShellAuthedSSlugMemberSettingsIndexRoute,
    ShellAuthedSSlugMemberTeamIndexRoute: ShellAuthedSSlugMemberTeamIndexRoute,
  }

const ShellAuthedSSlugMemberRouteRouteWithChildren =
  ShellAuthedSSlugMemberRouteRoute._addFileChildren(
    ShellAuthedSSlugMemberRouteRouteChildren,
  )

interface ShellAuthedSSlugRouteRouteChildren {
  ShellAuthedSSlugMemberRouteRoute: typeof ShellAuthedSSlugMemberRouteRouteWithChildren
  ShellAuthedSSlugIndexRoute: typeof ShellAuthedSSlugIndexRoute
  ShellAuthedSSlugTrialsTrialCycleIdRoute: typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
}

const ShellAuthedSSlugRouteRouteChildren: ShellAuthedSSlugRouteRouteChildren = {
  ShellAuthedSSlugMemberRouteRoute:
    ShellAuthedSSlugMemberRouteRouteWithChildren,
  ShellAuthedSSlugIndexRoute: ShellAuthedSSlugIndexRoute,
  ShellAuthedSSlugTrialsTrialCycleIdRoute:
    ShellAuthedSSlugTrialsTrialCycleIdRoute,
}

const ShellAuthedSSlugRouteRouteWithChildren =
  ShellAuthedSSlugRouteRoute._addFileChildren(
    ShellAuthedSSlugRouteRouteChildren,
  )

interface ShellAuthedRouteRouteChildren {
  ShellAuthedSSlugRouteRoute: typeof ShellAuthedSSlugRouteRouteWithChildren
  ShellAuthedStartupsNewRoute: typeof ShellAuthedStartupsNewRoute
  ShellAuthedInboxIndexRoute: typeof ShellAuthedInboxIndexRoute
  ShellAuthedMyPulsesIndexRoute: typeof ShellAuthedMyPulsesIndexRoute
  ShellAuthedProfileIndexRoute: typeof ShellAuthedProfileIndexRoute
  ShellAuthedThreadsIndexRoute: typeof ShellAuthedThreadsIndexRoute
}

const ShellAuthedRouteRouteChildren: ShellAuthedRouteRouteChildren = {
  ShellAuthedSSlugRouteRoute: ShellAuthedSSlugRouteRouteWithChildren,
  ShellAuthedStartupsNewRoute: ShellAuthedStartupsNewRoute,
  ShellAuthedInboxIndexRoute: ShellAuthedInboxIndexRoute,
  ShellAuthedMyPulsesIndexRoute: ShellAuthedMyPulsesIndexRoute,
  ShellAuthedProfileIndexRoute: ShellAuthedProfileIndexRoute,
  ShellAuthedThreadsIndexRoute: ShellAuthedThreadsIndexRoute,
}

const ShellAuthedRouteRouteWithChildren =
  ShellAuthedRouteRoute._addFileChildren(ShellAuthedRouteRouteChildren)

interface ShellRouteRouteChildren {
  ShellAuthedRouteRoute: typeof ShellAuthedRouteRouteWithChildren
  ShellStartupSlugRoute: typeof ShellStartupSlugRoute
  ShellDiscoverIndexRoute: typeof ShellDiscoverIndexRoute
  ShellPricingIndexRoute: typeof ShellPricingIndexRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellAuthedRouteRoute: ShellAuthedRouteRouteWithChildren,
  ShellStartupSlugRoute: ShellStartupSlugRoute,
  ShellDiscoverIndexRoute: ShellDiscoverIndexRoute,
  ShellPricingIndexRoute: ShellPricingIndexRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppStartupsNewRoute: typeof AppStartupsNewRoute
  AppTrialsTrialCycleIdRoute: typeof AppTrialsTrialCycleIdRoute
  AppExploreIndexRoute: typeof AppExploreIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppStartupIndexRoute: typeof AppStartupIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppTrialsIndexRoute: typeof AppTrialsIndexRoute
  AppUpgradeIndexRoute: typeof AppUpgradeIndexRoute
  AppWorkIndexRoute: typeof AppWorkIndexRoute
  AppStartupRolesNewRoute: typeof AppStartupRolesNewRoute
  AppStartupTrialsNewRoute: typeof AppStartupTrialsNewRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppStartupsNewRoute: AppStartupsNewRoute,
  AppTrialsTrialCycleIdRoute: AppTrialsTrialCycleIdRoute,
  AppExploreIndexRoute: AppExploreIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppStartupIndexRoute: AppStartupIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppTrialsIndexRoute: AppTrialsIndexRoute,
  AppUpgradeIndexRoute: AppUpgradeIndexRoute,
  AppWorkIndexRoute: AppWorkIndexRoute,
  AppStartupRolesNewRoute: AppStartupRolesNewRoute,
  AppStartupTrialsNewRoute: AppStartupTrialsNewRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRouteRoute: ShellRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  UUsernameRoute: UUsernameRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
