/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as ShellAuthedRouteRouteImport } from './routes/_shell/_authed/route'
import { Route as ShellDiscoverIndexRouteImport } from './routes/_shell/discover/index'
import { Route as ShellHackathonsTrialCycleIdRouteImport } from './routes/_shell/hackathons/$trialCycleId'
import { Route as ShellInviteTokenRouteImport } from './routes/_shell/invite/$token'
import { Route as ShellPricingIndexRouteImport } from './routes/_shell/pricing/index'
import { Route as ShellStartupSlugRouteImport } from './routes/_shell/startup/$slug'
import { Route as ShellUUsernameRouteImport } from './routes/_shell/u/$username'
import { Route as ShellAuthedInboxIndexRouteImport } from './routes/_shell/_authed/inbox/index'
import { Route as ShellAuthedMyEntriesIndexRouteImport } from './routes/_shell/_authed/my-entries/index'
import { Route as ShellAuthedMyPulsesIndexRouteImport } from './routes/_shell/_authed/my-pulses/index'
import { Route as ShellAuthedProfileIndexRouteImport } from './routes/_shell/_authed/profile/index'
import { Route as ShellAuthedSSlugRouteRouteImport } from './routes/_shell/_authed/s/$slug/route'
import { Route as ShellAuthedStartupsNewRouteImport } from './routes/_shell/_authed/startups/new'
import { Route as ShellAuthedThreadsIndexRouteImport } from './routes/_shell/_authed/threads/index'
import { Route as ShellAuthedThreadsTrialCycleIdRouteImport } from './routes/_shell/_authed/threads/$trialCycleId'
import { Route as ShellAuthedSSlugIndexRouteImport } from './routes/_shell/_authed/s/$slug/index'
import { Route as ShellAuthedSSlugMemberRouteRouteImport } from './routes/_shell/_authed/s/$slug/_member/route'
import { Route as ShellAuthedSSlugTrialsTrialCycleIdRouteImport } from './routes/_shell/_authed/s/$slug/trials/$trialCycleId'
import { Route as ShellAuthedSSlugMemberActivityIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/activity/index'
import { Route as ShellAuthedSSlugMemberCyclesIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/cycles/index'
import { Route as ShellAuthedSSlugMemberCyclesCycleIdRouteImport } from './routes/_shell/_authed/s/$slug/_member/cycles/$cycleId'
import { Route as ShellAuthedSSlugMemberHiringIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/hiring/index'
import { Route as ShellAuthedSSlugMemberHiringNewRouteImport } from './routes/_shell/_authed/s/$slug/_member/hiring/new'
import { Route as ShellAuthedSSlugMemberPitchIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/pitch/index'
import { Route as ShellAuthedSSlugMemberSettingsIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/settings/index'
import { Route as ShellAuthedSSlugMemberTeamIndexRouteImport } from './routes/_shell/_authed/s/$slug/_member/team/index'
import { Route as ShellAuthedSSlugMemberHiringTrialCycleIdEditRouteImport } from './routes/_shell/_authed/s/$slug/_member/hiring/$trialCycleId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAuthedRouteRoute = ShellAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellDiscoverIndexRoute = ShellDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellHackathonsTrialCycleIdRoute =
  ShellHackathonsTrialCycleIdRouteImport.update({
    id: '/hackathons/$trialCycleId',
    path: '/hackathons/$trialCycleId',
    getParentRoute: () => ShellRouteRoute,
  } as any)
const ShellInviteTokenRoute = ShellInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPricingIndexRoute = ShellPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellStartupSlugRoute = ShellStartupSlugRouteImport.update({
  id: '/startup/$slug',
  path: '/startup/$slug',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellUUsernameRoute = ShellUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellAuthedInboxIndexRoute = ShellAuthedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedMyEntriesIndexRoute =
  ShellAuthedMyEntriesIndexRouteImport.update({
    id: '/my-entries/',
    path: '/my-entries/',
    getParentRoute: () => ShellAuthedRouteRoute,
  } as any)
const ShellAuthedMyPulsesIndexRoute =
  ShellAuthedMyPulsesIndexRouteImport.update({
    id: '/my-pulses/',
    path: '/my-pulses/',
    getParentRoute: () => ShellAuthedRouteRoute,
  } as any)
const ShellAuthedProfileIndexRoute = ShellAuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedSSlugRouteRoute = ShellAuthedSSlugRouteRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedStartupsNewRoute = ShellAuthedStartupsNewRouteImport.update({
  id: '/startups/new',
  path: '/startups/new',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedThreadsIndexRoute = ShellAuthedThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => ShellAuthedRouteRoute,
} as any)
const ShellAuthedThreadsTrialCycleIdRoute =
  ShellAuthedThreadsTrialCycleIdRouteImport.update({
    id: '/threads/$trialCycleId',
    path: '/threads/$trialCycleId',
    getParentRoute: () => ShellAuthedRouteRoute,
  } as any)
const ShellAuthedSSlugIndexRoute = ShellAuthedSSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAuthedSSlugRouteRoute,
} as any)
const ShellAuthedSSlugMemberRouteRoute =
  ShellAuthedSSlugMemberRouteRouteImport.update({
    id: '/_member',
    getParentRoute: () => ShellAuthedSSlugRouteRoute,
  } as any)
const ShellAuthedSSlugTrialsTrialCycleIdRoute =
  ShellAuthedSSlugTrialsTrialCycleIdRouteImport.update({
    id: '/trials/$trialCycleId',
    path: '/trials/$trialCycleId',
    getParentRoute: () => ShellAuthedSSlugRouteRoute,
  } as any)
const ShellAuthedSSlugMemberActivityIndexRoute =
  ShellAuthedSSlugMemberActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberCyclesIndexRoute =
  ShellAuthedSSlugMemberCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberCyclesCycleIdRoute =
  ShellAuthedSSlugMemberCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberHiringIndexRoute =
  ShellAuthedSSlugMemberHiringIndexRouteImport.update({
    id: '/hiring/',
    path: '/hiring/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberHiringNewRoute =
  ShellAuthedSSlugMemberHiringNewRouteImport.update({
    id: '/hiring/new',
    path: '/hiring/new',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberPitchIndexRoute =
  ShellAuthedSSlugMemberPitchIndexRouteImport.update({
    id: '/pitch/',
    path: '/pitch/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberSettingsIndexRoute =
  ShellAuthedSSlugMemberSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberTeamIndexRoute =
  ShellAuthedSSlugMemberTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)
const ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute =
  ShellAuthedSSlugMemberHiringTrialCycleIdEditRouteImport.update({
    id: '/hiring/$trialCycleId/edit',
    path: '/hiring/$trialCycleId/edit',
    getParentRoute: () => ShellAuthedSSlugMemberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hackathons/$trialCycleId': typeof ShellHackathonsTrialCycleIdRoute
  '/invite/$token': typeof ShellInviteTokenRoute
  '/startup/$slug': typeof ShellStartupSlugRoute
  '/u/$username': typeof ShellUUsernameRoute
  '/discover/': typeof ShellDiscoverIndexRoute
  '/pricing/': typeof ShellPricingIndexRoute
  '/s/$slug': typeof ShellAuthedSSlugRouteRouteWithChildren
  '/startups/new': typeof ShellAuthedStartupsNewRoute
  '/threads/$trialCycleId': typeof ShellAuthedThreadsTrialCycleIdRoute
  '/inbox/': typeof ShellAuthedInboxIndexRoute
  '/my-entries/': typeof ShellAuthedMyEntriesIndexRoute
  '/my-pulses/': typeof ShellAuthedMyPulsesIndexRoute
  '/profile/': typeof ShellAuthedProfileIndexRoute
  '/threads/': typeof ShellAuthedThreadsIndexRoute
  '/s/$slug/': typeof ShellAuthedSSlugIndexRoute
  '/s/$slug/trials/$trialCycleId': typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
  '/s/$slug/cycles/$cycleId': typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  '/s/$slug/hiring/new': typeof ShellAuthedSSlugMemberHiringNewRoute
  '/s/$slug/activity/': typeof ShellAuthedSSlugMemberActivityIndexRoute
  '/s/$slug/cycles/': typeof ShellAuthedSSlugMemberCyclesIndexRoute
  '/s/$slug/hiring/': typeof ShellAuthedSSlugMemberHiringIndexRoute
  '/s/$slug/pitch/': typeof ShellAuthedSSlugMemberPitchIndexRoute
  '/s/$slug/settings/': typeof ShellAuthedSSlugMemberSettingsIndexRoute
  '/s/$slug/team/': typeof ShellAuthedSSlugMemberTeamIndexRoute
  '/s/$slug/hiring/$trialCycleId/edit': typeof ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hackathons/$trialCycleId': typeof ShellHackathonsTrialCycleIdRoute
  '/invite/$token': typeof ShellInviteTokenRoute
  '/startup/$slug': typeof ShellStartupSlugRoute
  '/u/$username': typeof ShellUUsernameRoute
  '/discover': typeof ShellDiscoverIndexRoute
  '/pricing': typeof ShellPricingIndexRoute
  '/startups/new': typeof ShellAuthedStartupsNewRoute
  '/threads/$trialCycleId': typeof ShellAuthedThreadsTrialCycleIdRoute
  '/inbox': typeof ShellAuthedInboxIndexRoute
  '/my-entries': typeof ShellAuthedMyEntriesIndexRoute
  '/my-pulses': typeof ShellAuthedMyPulsesIndexRoute
  '/profile': typeof ShellAuthedProfileIndexRoute
  '/threads': typeof ShellAuthedThreadsIndexRoute
  '/s/$slug': typeof ShellAuthedSSlugIndexRoute
  '/s/$slug/trials/$trialCycleId': typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
  '/s/$slug/cycles/$cycleId': typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  '/s/$slug/hiring/new': typeof ShellAuthedSSlugMemberHiringNewRoute
  '/s/$slug/activity': typeof ShellAuthedSSlugMemberActivityIndexRoute
  '/s/$slug/cycles': typeof ShellAuthedSSlugMemberCyclesIndexRoute
  '/s/$slug/hiring': typeof ShellAuthedSSlugMemberHiringIndexRoute
  '/s/$slug/pitch': typeof ShellAuthedSSlugMemberPitchIndexRoute
  '/s/$slug/settings': typeof ShellAuthedSSlugMemberSettingsIndexRoute
  '/s/$slug/team': typeof ShellAuthedSSlugMemberTeamIndexRoute
  '/s/$slug/hiring/$trialCycleId/edit': typeof ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteRouteWithChildren
  '/_shell/_authed': typeof ShellAuthedRouteRouteWithChildren
  '/_shell/hackathons/$trialCycleId': typeof ShellHackathonsTrialCycleIdRoute
  '/_shell/invite/$token': typeof ShellInviteTokenRoute
  '/_shell/startup/$slug': typeof ShellStartupSlugRoute
  '/_shell/u/$username': typeof ShellUUsernameRoute
  '/_shell/discover/': typeof ShellDiscoverIndexRoute
  '/_shell/pricing/': typeof ShellPricingIndexRoute
  '/_shell/_authed/s/$slug': typeof ShellAuthedSSlugRouteRouteWithChildren
  '/_shell/_authed/startups/new': typeof ShellAuthedStartupsNewRoute
  '/_shell/_authed/threads/$trialCycleId': typeof ShellAuthedThreadsTrialCycleIdRoute
  '/_shell/_authed/inbox/': typeof ShellAuthedInboxIndexRoute
  '/_shell/_authed/my-entries/': typeof ShellAuthedMyEntriesIndexRoute
  '/_shell/_authed/my-pulses/': typeof ShellAuthedMyPulsesIndexRoute
  '/_shell/_authed/profile/': typeof ShellAuthedProfileIndexRoute
  '/_shell/_authed/threads/': typeof ShellAuthedThreadsIndexRoute
  '/_shell/_authed/s/$slug/_member': typeof ShellAuthedSSlugMemberRouteRouteWithChildren
  '/_shell/_authed/s/$slug/': typeof ShellAuthedSSlugIndexRoute
  '/_shell/_authed/s/$slug/trials/$trialCycleId': typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
  '/_shell/_authed/s/$slug/_member/cycles/$cycleId': typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  '/_shell/_authed/s/$slug/_member/hiring/new': typeof ShellAuthedSSlugMemberHiringNewRoute
  '/_shell/_authed/s/$slug/_member/activity/': typeof ShellAuthedSSlugMemberActivityIndexRoute
  '/_shell/_authed/s/$slug/_member/cycles/': typeof ShellAuthedSSlugMemberCyclesIndexRoute
  '/_shell/_authed/s/$slug/_member/hiring/': typeof ShellAuthedSSlugMemberHiringIndexRoute
  '/_shell/_authed/s/$slug/_member/pitch/': typeof ShellAuthedSSlugMemberPitchIndexRoute
  '/_shell/_authed/s/$slug/_member/settings/': typeof ShellAuthedSSlugMemberSettingsIndexRoute
  '/_shell/_authed/s/$slug/_member/team/': typeof ShellAuthedSSlugMemberTeamIndexRoute
  '/_shell/_authed/s/$slug/_member/hiring/$trialCycleId/edit': typeof ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hackathons/$trialCycleId'
    | '/invite/$token'
    | '/startup/$slug'
    | '/u/$username'
    | '/discover/'
    | '/pricing/'
    | '/s/$slug'
    | '/startups/new'
    | '/threads/$trialCycleId'
    | '/inbox/'
    | '/my-entries/'
    | '/my-pulses/'
    | '/profile/'
    | '/threads/'
    | '/s/$slug/'
    | '/s/$slug/trials/$trialCycleId'
    | '/s/$slug/cycles/$cycleId'
    | '/s/$slug/hiring/new'
    | '/s/$slug/activity/'
    | '/s/$slug/cycles/'
    | '/s/$slug/hiring/'
    | '/s/$slug/pitch/'
    | '/s/$slug/settings/'
    | '/s/$slug/team/'
    | '/s/$slug/hiring/$trialCycleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hackathons/$trialCycleId'
    | '/invite/$token'
    | '/startup/$slug'
    | '/u/$username'
    | '/discover'
    | '/pricing'
    | '/startups/new'
    | '/threads/$trialCycleId'
    | '/inbox'
    | '/my-entries'
    | '/my-pulses'
    | '/profile'
    | '/threads'
    | '/s/$slug'
    | '/s/$slug/trials/$trialCycleId'
    | '/s/$slug/cycles/$cycleId'
    | '/s/$slug/hiring/new'
    | '/s/$slug/activity'
    | '/s/$slug/cycles'
    | '/s/$slug/hiring'
    | '/s/$slug/pitch'
    | '/s/$slug/settings'
    | '/s/$slug/team'
    | '/s/$slug/hiring/$trialCycleId/edit'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/_authed'
    | '/_shell/hackathons/$trialCycleId'
    | '/_shell/invite/$token'
    | '/_shell/startup/$slug'
    | '/_shell/u/$username'
    | '/_shell/discover/'
    | '/_shell/pricing/'
    | '/_shell/_authed/s/$slug'
    | '/_shell/_authed/startups/new'
    | '/_shell/_authed/threads/$trialCycleId'
    | '/_shell/_authed/inbox/'
    | '/_shell/_authed/my-entries/'
    | '/_shell/_authed/my-pulses/'
    | '/_shell/_authed/profile/'
    | '/_shell/_authed/threads/'
    | '/_shell/_authed/s/$slug/_member'
    | '/_shell/_authed/s/$slug/'
    | '/_shell/_authed/s/$slug/trials/$trialCycleId'
    | '/_shell/_authed/s/$slug/_member/cycles/$cycleId'
    | '/_shell/_authed/s/$slug/_member/hiring/new'
    | '/_shell/_authed/s/$slug/_member/activity/'
    | '/_shell/_authed/s/$slug/_member/cycles/'
    | '/_shell/_authed/s/$slug/_member/hiring/'
    | '/_shell/_authed/s/$slug/_member/pitch/'
    | '/_shell/_authed/s/$slug/_member/settings/'
    | '/_shell/_authed/s/$slug/_member/team/'
    | '/_shell/_authed/s/$slug/_member/hiring/$trialCycleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_authed': {
      id: '/_shell/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellAuthedRouteRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/discover/': {
      id: '/_shell/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof ShellDiscoverIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/hackathons/$trialCycleId': {
      id: '/_shell/hackathons/$trialCycleId'
      path: '/hackathons/$trialCycleId'
      fullPath: '/hackathons/$trialCycleId'
      preLoaderRoute: typeof ShellHackathonsTrialCycleIdRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/invite/$token': {
      id: '/_shell/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof ShellInviteTokenRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/pricing/': {
      id: '/_shell/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof ShellPricingIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/startup/$slug': {
      id: '/_shell/startup/$slug'
      path: '/startup/$slug'
      fullPath: '/startup/$slug'
      preLoaderRoute: typeof ShellStartupSlugRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/u/$username': {
      id: '/_shell/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof ShellUUsernameRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/_authed/inbox/': {
      id: '/_shell/_authed/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof ShellAuthedInboxIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/my-entries/': {
      id: '/_shell/_authed/my-entries/'
      path: '/my-entries'
      fullPath: '/my-entries/'
      preLoaderRoute: typeof ShellAuthedMyEntriesIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/my-pulses/': {
      id: '/_shell/_authed/my-pulses/'
      path: '/my-pulses'
      fullPath: '/my-pulses/'
      preLoaderRoute: typeof ShellAuthedMyPulsesIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/profile/': {
      id: '/_shell/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ShellAuthedProfileIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/s/$slug': {
      id: '/_shell/_authed/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof ShellAuthedSSlugRouteRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/startups/new': {
      id: '/_shell/_authed/startups/new'
      path: '/startups/new'
      fullPath: '/startups/new'
      preLoaderRoute: typeof ShellAuthedStartupsNewRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/threads/': {
      id: '/_shell/_authed/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ShellAuthedThreadsIndexRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/threads/$trialCycleId': {
      id: '/_shell/_authed/threads/$trialCycleId'
      path: '/threads/$trialCycleId'
      fullPath: '/threads/$trialCycleId'
      preLoaderRoute: typeof ShellAuthedThreadsTrialCycleIdRouteImport
      parentRoute: typeof ShellAuthedRouteRoute
    }
    '/_shell/_authed/s/$slug/': {
      id: '/_shell/_authed/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof ShellAuthedSSlugIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugRouteRoute
    }
    '/_shell/_authed/s/$slug/_member': {
      id: '/_shell/_authed/s/$slug/_member'
      path: ''
      fullPath: '/s/$slug'
      preLoaderRoute: typeof ShellAuthedSSlugMemberRouteRouteImport
      parentRoute: typeof ShellAuthedSSlugRouteRoute
    }
    '/_shell/_authed/s/$slug/trials/$trialCycleId': {
      id: '/_shell/_authed/s/$slug/trials/$trialCycleId'
      path: '/trials/$trialCycleId'
      fullPath: '/s/$slug/trials/$trialCycleId'
      preLoaderRoute: typeof ShellAuthedSSlugTrialsTrialCycleIdRouteImport
      parentRoute: typeof ShellAuthedSSlugRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/activity/': {
      id: '/_shell/_authed/s/$slug/_member/activity/'
      path: '/activity'
      fullPath: '/s/$slug/activity/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberActivityIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/cycles/': {
      id: '/_shell/_authed/s/$slug/_member/cycles/'
      path: '/cycles'
      fullPath: '/s/$slug/cycles/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberCyclesIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/cycles/$cycleId': {
      id: '/_shell/_authed/s/$slug/_member/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/s/$slug/cycles/$cycleId'
      preLoaderRoute: typeof ShellAuthedSSlugMemberCyclesCycleIdRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/hiring/': {
      id: '/_shell/_authed/s/$slug/_member/hiring/'
      path: '/hiring'
      fullPath: '/s/$slug/hiring/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberHiringIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/hiring/new': {
      id: '/_shell/_authed/s/$slug/_member/hiring/new'
      path: '/hiring/new'
      fullPath: '/s/$slug/hiring/new'
      preLoaderRoute: typeof ShellAuthedSSlugMemberHiringNewRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/pitch/': {
      id: '/_shell/_authed/s/$slug/_member/pitch/'
      path: '/pitch'
      fullPath: '/s/$slug/pitch/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberPitchIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/settings/': {
      id: '/_shell/_authed/s/$slug/_member/settings/'
      path: '/settings'
      fullPath: '/s/$slug/settings/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberSettingsIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/team/': {
      id: '/_shell/_authed/s/$slug/_member/team/'
      path: '/team'
      fullPath: '/s/$slug/team/'
      preLoaderRoute: typeof ShellAuthedSSlugMemberTeamIndexRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
    '/_shell/_authed/s/$slug/_member/hiring/$trialCycleId/edit': {
      id: '/_shell/_authed/s/$slug/_member/hiring/$trialCycleId/edit'
      path: '/hiring/$trialCycleId/edit'
      fullPath: '/s/$slug/hiring/$trialCycleId/edit'
      preLoaderRoute: typeof ShellAuthedSSlugMemberHiringTrialCycleIdEditRouteImport
      parentRoute: typeof ShellAuthedSSlugMemberRouteRoute
    }
  }
}

interface ShellAuthedSSlugMemberRouteRouteChildren {
  ShellAuthedSSlugMemberCyclesCycleIdRoute: typeof ShellAuthedSSlugMemberCyclesCycleIdRoute
  ShellAuthedSSlugMemberHiringNewRoute: typeof ShellAuthedSSlugMemberHiringNewRoute
  ShellAuthedSSlugMemberActivityIndexRoute: typeof ShellAuthedSSlugMemberActivityIndexRoute
  ShellAuthedSSlugMemberCyclesIndexRoute: typeof ShellAuthedSSlugMemberCyclesIndexRoute
  ShellAuthedSSlugMemberHiringIndexRoute: typeof ShellAuthedSSlugMemberHiringIndexRoute
  ShellAuthedSSlugMemberPitchIndexRoute: typeof ShellAuthedSSlugMemberPitchIndexRoute
  ShellAuthedSSlugMemberSettingsIndexRoute: typeof ShellAuthedSSlugMemberSettingsIndexRoute
  ShellAuthedSSlugMemberTeamIndexRoute: typeof ShellAuthedSSlugMemberTeamIndexRoute
  ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute: typeof ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute
}

const ShellAuthedSSlugMemberRouteRouteChildren: ShellAuthedSSlugMemberRouteRouteChildren =
  {
    ShellAuthedSSlugMemberCyclesCycleIdRoute:
      ShellAuthedSSlugMemberCyclesCycleIdRoute,
    ShellAuthedSSlugMemberHiringNewRoute: ShellAuthedSSlugMemberHiringNewRoute,
    ShellAuthedSSlugMemberActivityIndexRoute:
      ShellAuthedSSlugMemberActivityIndexRoute,
    ShellAuthedSSlugMemberCyclesIndexRoute:
      ShellAuthedSSlugMemberCyclesIndexRoute,
    ShellAuthedSSlugMemberHiringIndexRoute:
      ShellAuthedSSlugMemberHiringIndexRoute,
    ShellAuthedSSlugMemberPitchIndexRoute:
      ShellAuthedSSlugMemberPitchIndexRoute,
    ShellAuthedSSlugMemberSettingsIndexRoute:
      ShellAuthedSSlugMemberSettingsIndexRoute,
    ShellAuthedSSlugMemberTeamIndexRoute: ShellAuthedSSlugMemberTeamIndexRoute,
    ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute:
      ShellAuthedSSlugMemberHiringTrialCycleIdEditRoute,
  }

const ShellAuthedSSlugMemberRouteRouteWithChildren =
  ShellAuthedSSlugMemberRouteRoute._addFileChildren(
    ShellAuthedSSlugMemberRouteRouteChildren,
  )

interface ShellAuthedSSlugRouteRouteChildren {
  ShellAuthedSSlugMemberRouteRoute: typeof ShellAuthedSSlugMemberRouteRouteWithChildren
  ShellAuthedSSlugIndexRoute: typeof ShellAuthedSSlugIndexRoute
  ShellAuthedSSlugTrialsTrialCycleIdRoute: typeof ShellAuthedSSlugTrialsTrialCycleIdRoute
}

const ShellAuthedSSlugRouteRouteChildren: ShellAuthedSSlugRouteRouteChildren = {
  ShellAuthedSSlugMemberRouteRoute:
    ShellAuthedSSlugMemberRouteRouteWithChildren,
  ShellAuthedSSlugIndexRoute: ShellAuthedSSlugIndexRoute,
  ShellAuthedSSlugTrialsTrialCycleIdRoute:
    ShellAuthedSSlugTrialsTrialCycleIdRoute,
}

const ShellAuthedSSlugRouteRouteWithChildren =
  ShellAuthedSSlugRouteRoute._addFileChildren(
    ShellAuthedSSlugRouteRouteChildren,
  )

interface ShellAuthedRouteRouteChildren {
  ShellAuthedSSlugRouteRoute: typeof ShellAuthedSSlugRouteRouteWithChildren
  ShellAuthedStartupsNewRoute: typeof ShellAuthedStartupsNewRoute
  ShellAuthedThreadsTrialCycleIdRoute: typeof ShellAuthedThreadsTrialCycleIdRoute
  ShellAuthedInboxIndexRoute: typeof ShellAuthedInboxIndexRoute
  ShellAuthedMyEntriesIndexRoute: typeof ShellAuthedMyEntriesIndexRoute
  ShellAuthedMyPulsesIndexRoute: typeof ShellAuthedMyPulsesIndexRoute
  ShellAuthedProfileIndexRoute: typeof ShellAuthedProfileIndexRoute
  ShellAuthedThreadsIndexRoute: typeof ShellAuthedThreadsIndexRoute
}

const ShellAuthedRouteRouteChildren: ShellAuthedRouteRouteChildren = {
  ShellAuthedSSlugRouteRoute: ShellAuthedSSlugRouteRouteWithChildren,
  ShellAuthedStartupsNewRoute: ShellAuthedStartupsNewRoute,
  ShellAuthedThreadsTrialCycleIdRoute: ShellAuthedThreadsTrialCycleIdRoute,
  ShellAuthedInboxIndexRoute: ShellAuthedInboxIndexRoute,
  ShellAuthedMyEntriesIndexRoute: ShellAuthedMyEntriesIndexRoute,
  ShellAuthedMyPulsesIndexRoute: ShellAuthedMyPulsesIndexRoute,
  ShellAuthedProfileIndexRoute: ShellAuthedProfileIndexRoute,
  ShellAuthedThreadsIndexRoute: ShellAuthedThreadsIndexRoute,
}

const ShellAuthedRouteRouteWithChildren =
  ShellAuthedRouteRoute._addFileChildren(ShellAuthedRouteRouteChildren)

interface ShellRouteRouteChildren {
  ShellAuthedRouteRoute: typeof ShellAuthedRouteRouteWithChildren
  ShellHackathonsTrialCycleIdRoute: typeof ShellHackathonsTrialCycleIdRoute
  ShellInviteTokenRoute: typeof ShellInviteTokenRoute
  ShellStartupSlugRoute: typeof ShellStartupSlugRoute
  ShellUUsernameRoute: typeof ShellUUsernameRoute
  ShellDiscoverIndexRoute: typeof ShellDiscoverIndexRoute
  ShellPricingIndexRoute: typeof ShellPricingIndexRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellAuthedRouteRoute: ShellAuthedRouteRouteWithChildren,
  ShellHackathonsTrialCycleIdRoute: ShellHackathonsTrialCycleIdRoute,
  ShellInviteTokenRoute: ShellInviteTokenRoute,
  ShellStartupSlugRoute: ShellStartupSlugRoute,
  ShellUUsernameRoute: ShellUUsernameRoute,
  ShellDiscoverIndexRoute: ShellDiscoverIndexRoute,
  ShellPricingIndexRoute: ShellPricingIndexRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRouteRoute: ShellRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
